sudo: required
services:
- docker
before_install:
- docker-compose build api-prod
- docker-compose run api-prod npm install
script:
- docker-compose run api-prod npm run build
deploy:
  provider: heroku
  api_key:
    secure: EzmSg48qOw05RBTjdJ6bN+/XKRDEM5L1907IAO9j4RBCQyt6vRRqGraV7S2tWJDfyHp42FiHfS6cgepihSnSDpxQ/ldYk4mwIuAUi7SLR5kcFAzmPzyKIUYdYairf0UtZG70+lbfNAK7tUjRJt7jNj7oMz1ZvrNZH7FZfbEEB795ZP9Cgk5e5ROtS+zMO0DWlEjA8jZUrSQpF1OzPkUkqVVXtSg7yNie/aChUH61wdQDmUWSUpQhj8yZBptYkzbhwSD4WAqV62u/zFzk+HTdRL2PRFccc8VYYuNNEwFl8aLuDkbjZcBY84cm6TWTQHYKVslD6ejlH+ucLz8MzbrQBbel/ToI35MGCASnkA9/PWOhNcMVvUfsN+C5A9fJhzlByto03M4V4BgSP7hCvWVh2WKMje1obg/H3cLQ073s7e8RcrJksxFNQoEUGP2Jg11bWxlyKqWcctb5bwVY0CgbVb7Pe1+rC++FMvOvM8rXvrWUH1KbmKmMC7LtAwmNW6TjV8I3FUkoNr9tuodb3gSghcPsiUMYWlyfEVtkasRjAyzXZN/XNMiW8kS+AsZzTEc2+QZVVF1W7cHuSbu3VYHG91gHjL7MB3vR4paAuF9n2c6ewKf3QijIQGYADlBBs0Gb03h/KKHJS5LXe254E9RrbMJendnP7DwjuJwot+h+Rxw=
  app: advanced2heroku
  script: bash heroku.sh
notifications:
  email: false
