version: '3'
services:
  api:
    build: .
    env_file: .env
    ports:
     - "6001:3001"
    links:
     - mongo
    volumes:
     - ./:/usr/src/app
  mongo:
    image: "mongo:3.6"
    ports:
     - "6002:27017"
