version: '3'
services:
  api:
    image: api
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    ports:
     - "6001:3001"
    links:
     - mongo
    volumes:
     - ./:/usr/src/app
  api-prod:
    image: api
    build:
      dockerfile: Dockerfile-travis
      context: .
    env_file: .env
    ports:
     - "6001:3001"
    links:
     - mongo
    volumes:
     - ./:/usr/src/app

  mongo:
    image: "mongo:3.6"
    ports:
     - "6002:27017"

