export const AJAX_BEGIN = 'AJAX_BEGIN'
export const AJAX_ERROR = 'AJAX_ERROR'

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"

export const ITEMS_LOADED_SUCCESS = "ITEMS_LOADED_SUCCESS"
export const ITEM_CREATED_SUCCESS = "ITEM_CREATED_SUCCESS"

export const CART_LOADED_SUCCESS = "CART_LOADED_SUCCESS"
export const CART_ADDED_SUCCESS = "CART_ADDED_SUCCESS"
export const CART_DELETED_SUCCESS = "CART_ADDED_SUCCESS"
