export const AJAX_BEGIN = 'AJAX_BEGIN'
export const AJAX_ERROR = 'AJAX_ERROR'
export const AJAX_SUCCESS = 'AJAX_SUCCESS'

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"

export const ITEMS_LOADED_SUCCESS = "ITEMS_LOADED_SUCCESS"
export const ITEM_CREATED_SUCCESS = "ITEM_CREATED_SUCCESS"

//X defines no ajax call needed
export const CART_LOADED_SUCCESSX = "CART_LOADED_SUCCESSX"
export const CART_ADDED_SUCCESSX = "CART_ADDED_SUCCESSX"
export const CART_DELETED_SUCCESSX = "CART_ADDED_SUCCESSX"
export const CART_BOUGHT_SUCCESS = "CART_BOUGHT_SUCCESS"

